class ValidationError(Exception):
    pass

class ChainError(Exception):
    pass
